const facts = [
  ["Filed", "August 19, 2026"], ["Forum", "N.D. California"],
  ["Docket", "4:26-cv-08658"], ["Matter", "Patent infringement"],
];

const patents = [
  ["U.S. 9,248,221", "claim 5", "https://patents.google.com/patent/US9248221B2/en"],
  ["U.S. 9,895,473", "claim 1", "https://patents.google.com/patent/US9895473B2/en"],
  ["U.S. 10,603,415", "claim 1", "https://patents.google.com/patent/US10603415B2/en"],
  ["U.S. 11,678,896", "claim 1", "https://patents.google.com/patent/US11678896B2/en"],
  ["U.S. 12,539,127", "claim 11", "https://patents.google.com/patent/US12539127B2/en"],
];

const issues = [
  {n:"01", t:"Pressure-pattern detection", q:"Does THUNDERBOLT identify the claimed sequence of multiple vacuum-pressure increases and decreases, rather than pump ripple, noise, or an arbitrary fluctuation?", p:"Source code; sampling and filtering specifications; logged traces; controlled clot and occlusion testing.", d:"Biofluid mechanics · signal processing"},
  {n:"02", t:"Baseline, peak and threshold", q:"How are baseline and peak pressure established, and is their difference compared with a stored threshold by the accused logic?", p:"Firmware; memory parameters; validation protocols; repeatable waveform analysis.", d:"Controls · embedded systems"},
  {n:"03", t:"Fluid-path configuration", q:"Do the pressure sensor, tubing, module, catheter and vacuum source satisfy the claimed fluid-communication and inline/removable arrangements?", p:"Teardown; schematics; fluid-path inspection; sensor characterization.", d:"Device engineering · MEMS"},
  {n:"04", t:"Alerts and state transitions", q:"Are visual and audible outputs tied to the claimed fluctuation-present and fluctuation-no-longer-present states?", p:"Event logs; source code; IFUs; synchronized bench video and data.", d:"Embedded systems · human factors"},
  {n:"05", t:"Clinical and physical variables", q:"Which catheter, clot, blood-analog, tubing-compliance, pump and operator variables materially change the pressure signature?", p:"Validated matrix across clot analogs, vessel geometries, catheter sizes, noise and occlusion states.", d:"Thrombectomy · vascular biomechanics"},
  {n:"06", t:"Instructions and induced use", q:"Do public instructions, demonstrations or training direct clinicians through every step of asserted method claims?", p:"IFUs; training; launch materials; demonstrations; clinician testimony mapped element by element.", d:"Neurointervention · clinical workflow"},
  {n:"07", t:"Priority-date technical baseline", q:"What would a skilled person have understood about aspiration-pressure monitoring, thresholds and clot detection at the priority date?", p:"Family history; contemporaneous literature; earlier devices and systems; defensible POSITA definition.", d:"Prior art · device history"},
  {n:"08", t:"Technical provenance and notice", q:"What was conveyed in the alleged 2016 NDA-era meeting and 2026 notices, and does the engineering record reflect it?", p:"Meeting materials; design timelines; version control; inventor and engineer testimony.", d:"Medical-device development"},
];

const experts = [
  {r:1,n:"Matthew J. Gounis, PhD",salutation:"Dr. Gounis",email:"Matthew.Gounis@umassmed.edu",emailSource:"https://shriver.umassmed.edu/about/faculty-staff/",role:"Professor of Radiology; Director, New England Center for Stroke Research, UMass Chan",fit:"Experimental fluid mechanics, preclinical stroke-device evaluation, aspiration thrombectomy, clot-device interaction.",work:"Leads a translational stroke-research center; extensive thrombectomy-device and model publications.",lit:"No public patent-litigation testimony located in this bounded review.",risk:"Primarily engineering/preclinical rather than a practicing operator; industry funding and collaborations require diligence.",links:[["UMass NECStR","https://www.umassmed.edu/necstr/personnel/"],["Research profile","https://profiles.umassmed.edu/display/133595"]]},
  {r:2,n:"Michael Chen, MD",salutation:"Dr. Chen",email:"Michael_Chen@rush.edu",emailSource:"https://pubmed.ncbi.nlm.nih.gov/40010851/",role:"Professor of Neurology, Neurosurgery and Radiology, Rush University Medical Center",fit:"Practicing neurointerventionalist with aspiration-thrombectomy research and device-study leadership.",work:"National PI on an aspiration stroke study; published on endovascular devices and thrombectomy practice.",lit:"Declaration and deposition for RapidPulse in Penumbra v. RapidPulse PTAB proceedings.",risk:"Prior work adverse to Penumbra raises confidentiality, conflict and repeat-engagement diligence; pair with an engineering expert.",links:[["Rush faculty","https://www.rushu.rush.edu/faculty/michael-chen-md"],["PTAB declaration","https://ptabdata.blob.core.windows.net/files/2021/IPR2021-01466/v46_Exhibit%202015%20-%20M.%20Chen%20Decl.%20ISO%20883%20Patent%20POR.pdf"]]},
  {r:3,n:"Ender A. Finol, PhD",salutation:"Dr. Finol",email:"ender.finol@utsa.edu",emailSource:"https://klesse.utsa.edu/faculty/profiles/finol-ender.html",role:"Zachry Endowed Chair; Chair of Mechanical, Aerospace and Industrial Engineering, UTSA",fit:"Vascular biomechanics, biofluid mechanics, computational fluid dynamics and device design.",work:"Cardiovascular computational/experimental modeling; Fellow of ASME, AHA, AIMBE and BMES.",lit:"Expert opinions and deposition for RapidPulse in a related Penumbra PTAB proceeding.",risk:"Prior RapidPulse engagement creates conflicts/confidentiality diligence; broader cardiovascular CFD is not the production algorithm.",links:[["UTSA faculty","https://klesse.utsa.edu/faculty/profiles/finol-ender.html"],["PTAB deposition","https://ptacts.uspto.gov/ptacts/public-informations/petitions/1549190/download-documents?artifactId=BKTneC3WGIAfUagmDSN0z_JaubG9KUV-zqF540N3eSBdJyNd8gvvbQg"]]},
  {r:4,n:"Nabil Simaan, PhD",salutation:"Dr. Simaan",email:"nabil.simaan@vanderbilt.edu",emailSource:"https://www.vanderbilt.edu/vise/people/nabil-simaan/",role:"Professor of Mechanical Engineering, Vanderbilt University",fit:"Surgical robotics, assistive perception, pressure sensing, signal classification and catheter-thrombus detection.",work:"Coauthored a 2024 proximal-pressure/vacuum-excitation study; inventor on related assistive-perception technology.",lit:"No public litigation testimony located in this bounded review.",risk:"Active inventorship in closely overlapping pressure-sensing technology creates substantial IP and neutrality diligence.",links:[["Vanderbilt profile","https://www.vanderbilt.edu/vise/people/nabil-simaan/"],["2024 study","https://pubmed.ncbi.nlm.nih.gov/38241109/"],["Patents","https://patents.justia.com/inventor/nabil-simaan"]]},
  {r:5,n:"Michael T. Froehler, MD, PhD",salutation:"Dr. Froehler",email:"m.froehler@vanderbilt.edu",emailSource:"https://wag.app.vanderbilt.edu/PublicPage/Faculty/Details/38479",role:"Associate Professor; Director, Cerebrovascular Program, Vanderbilt University Medical Center",fit:"Neurointerventional practice, stroke thrombectomy and translational fluid-mechanics research.",work:"Coauthored the 2025 review “Fluid mechanics of aspiration thrombectomy.”",lit:"No relevant public patent-litigation testimony located in this bounded review.",risk:"Clinical and trial relationships require diligence; firmware opinions likely require an engineering counterpart.",links:[["Vanderbilt Health","https://www.vanderbilthealth.com/doctors/froehler-michael"],["Fluid-mechanics review","https://pubmed.ncbi.nlm.nih.gov/40345798/"]]},
  {r:6,n:"Thomas W. Kenny, PhD",salutation:"Dr. Kenny",email:"kenny@cdr.stanford.edu",emailSource:"https://photonics.stanford.edu/people/thomas-kenny",role:"Richard W. Weiland Professor; Senior Associate Dean, Stanford School of Engineering",fit:"MEMS, sensors, microstructures, force and pressure measurement, and medical-device engineering.",work:"Longstanding Stanford sensor researcher and inventor in microfabricated sensing systems.",lit:"Public CV identifies more than ten expert matters, including medical devices and physiological sensors.",risk:"Not a thrombectomy clinician and no aspiration-specific paper located; requires a clinical or biofluids counterpart.",links:[["Stanford profile","https://me.stanford.edu/people/thomas-kenny"],["Public CV","https://ptacts.uspto.gov/ptacts/public-informations/petitions/1554241/download-documents?artifactId=Z5Rb8kGhHDFYmUDVBUa1N_P682MyZnXv3rltT4DwT3buDJP93DfDmPw"]]},
  {r:7,n:"Bryan Good, PhD",salutation:"Dr. Good",email:"bgood6@utk.edu",emailSource:"https://sites.google.com/view/utkcardiovascularbiomechanics",role:"Assistant Professor of Biomedical Engineering, University of Tennessee, Knoxville",fit:"Cardiovascular biomechanics, experimental and computational thrombectomy models, cyclic aspiration.",work:"Leads a cardiovascular biomechanics lab; coauthored the 2025 aspiration fluid-mechanics review.",lit:"No public litigation testimony located in this bounded review.",risk:"Relatively junior and no testifying record found; academic models need validation against production-device data.",links:[["UTK faculty","https://tickle.utk.edu/bme/faculty/bryan-good/"],["Fluid-mechanics review","https://pubmed.ncbi.nlm.nih.gov/40345798/"]]},
  {r:8,n:"Rohan V. Chitale, MD",salutation:"Dr. Chitale",email:"rohan.v.chitale@vumc.org",emailSource:"https://www.vanderbilt.edu/vise/people/rohan-chitale/",role:"Associate Professor of Neurological Surgery, Mechanical Engineering and Radiology, Vanderbilt",fit:"Neuroendovascular surgery, thrombectomy workflow, catheter-thrombus contact and pressure sensing.",work:"Coauthored the vacuum-excitation contact-detection study; named on related patent work.",lit:"No public litigation testimony located in this bounded review.",risk:"Closely overlapping inventorship creates IP/commercial-interest diligence; pair clinical views with signal-processing depth.",links:[["Vanderbilt profile","https://neurosurgerydept.vmcweb.org/person/rohan-v-chitale-md"],["2024 study","https://pubmed.ncbi.nlm.nih.gov/38241109/"]]},
  {r:9,n:"Robert D. Howe, PhD",salutation:"Dr. Howe",email:"howe@seas.harvard.edu",emailSource:"https://seas.harvard.edu/person/robert-howe",role:"Abbott and James Lawrence Professor of Engineering, Harvard University",fit:"Medical robotics, catheter force sensing, biomechanics, controls, haptics and sensor-guided intervention.",work:"Leads Harvard's BioRobotics Laboratory; published on robotic catheter systems with image guidance, force sensing and closed-loop control.",lit:"Public PTAB records show deposition testimony in Intuitive Surgical v. Ethicon concerning surgical-robotics technology.",risk:"Catheter work is cardiac/robotic rather than aspiration thrombectomy; pair with thrombectomy or biofluids expertise and review industry collaborations.",links:[["Harvard profile","https://seas.harvard.edu/person/robert-howe"],["Catheter force-sensing paper","https://biorobotics.harvard.edu/files/2024/01/Robotic-Catheter-Cardiac-Ablation-Combining-Ultrasound-Guidance-and-Force-Control-a6c2916adda6c61d.pdf"],["PTAB deposition","https://ptacts.uspto.gov/ptacts/public-informations/petitions/1530222/download-documents?artifactId=w5uGRH7Th2ExcCkR_yxM-3Or1KY0uTfMrhxeGt2wlwTD2J31tQxGD1c"]]},
  {r:10,n:"Robert J. Webster III, PhD",salutation:"Dr. Webster",email:"Robert.webster@vanderbilt.edu",emailSource:"https://www.vanderbilt.edu/vise/people/bob-webster/",role:"Richard A. Schroeder Professor; Senior Associate Provost for Commercialization and Technology Transfer, Vanderbilt",fit:"Surgical robotics, sensor-guided intervention, medical-device design, controls and technology translation.",work:"Heads Vanderbilt's Medical Engineering and Discovery Lab; Vanderbilt reports more than 75 patents/applications and two startups from his work.",lit:"No public expert-testimony record located in this bounded review.",risk:"No aspiration-thrombectomy publication located; extensive patenting, startups, licensing and industry work require commercial-interest and conflicts diligence.",links:[["Vanderbilt profile","https://www.vanderbilt.edu/vise/people/bob-webster/"],["2026 Vanderbilt profile","https://engineering.vanderbilt.edu/2026/01/29/surgical-robotics-pioneer-robert-webster-guides-life-saving-ideas-into-reality/"],["Public CV","https://static1.squarespace.com/static/661dc8f29cd91731ed8c0c8c/t/66e9eb2a197a7e4e146743aa/1726606122824/Robert%2BWebster%2BCV%2B-%2B2024.pdf"]]},
];

const sources = [
  ["Public docket","Justia — caption, docket, forum, filing date, complaint and counsel","https://dockets.justia.com/docket/california/candce/4%3A2026cv08658/476629"],
  ["Attorney contact","Bird Marella — Timothy B. Yoo official biography and professional email","https://www.birdmarella.com/attorneys/timothy-b-yoo/"],
  ["Regulatory record","FDA — THUNDERBOLT Aspiration Tubing, 510(k) K250690","https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfpmn/pmn.cfm?ID=K250690"],
  ["Company disclosure","Penumbra 2025 Form 10-K — revenue and thrombectomy business","https://www.sec.gov/Archives/edgar/data/1321732/000132173226000007/pen-20251231.htm"],
  ["Product record","Penumbra — THUNDERBOLT stroke clearance announcement","https://www.penumbrainc.com/penumbras-thunderbolt-receives-fda-clearance-bringing-computer-assisted-vacuum-thrombectomy-technology-to-stroke/"],
  ["Contemporaneous report","Bloomberg Law — complaint report","https://news.bloomberglaw.com/california-brief/incuvate-says-penumbra-infringed-blood-clot-detection-systems"],
];

function expertMailto(expert: (typeof experts)[number]) {
  const subject = "Incuvate v. Penumbra - potential expert consultation";
  const body = `${expert.salutation},

I am counsel for [party] in Incuvate, LLC v. Penumbra, Inc., No. 4:26-cv-08658 (N.D. Cal.), a patent matter concerning aspiration-pressure monitoring in thrombectomy systems.

I am reaching out regarding a potential expert consultation. Your public work in ${expert.fit.charAt(0).toLowerCase() + expert.fit.slice(1)} appears relevant to technical questions in the matter. Would you be open to a brief preliminary call, subject to an initial conflicts check?

No engagement is created by this inquiry. Please do not send confidential information at this stage.

Best,
[Attorney name]
[Firm]
[Phone]`;
  return `mailto:${expert.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
}

export default function Home() {
  return <main>
    <nav className="nav shell"><a className="brand" href="#top">ER<span>·01</span></a><div className="navlinks"><a href="#matter">Matter</a><a href="#claims">Asserted claims</a><a href="#issues">Technical issues</a><a href="#experts">Potential experts</a><a href="#sources">Sources</a></div></nav>
    <section id="top" className="hero shell"><div className="eyebrow"><span/> Preliminary expert research memorandum · Review copy</div><h1>Incuvate v. Penumbra</h1><p className="dek">Potential expert disciplines and candidates for a five-patent dispute concerning aspiration-pressure monitoring in Penumbra&apos;s THUNDERBOLT thrombectomy platform.</p><p className="label">Independent preliminary research based on public information.</p><div className="facts">{facts.map(([l,v])=><div key={l}><small>{l}</small><strong>{v}</strong></div>)}</div></section>

    <section id="matter" className="brief shell"><div className="section-no">01</div><div><p className="kicker">Preliminary assessment</p><h2>The principal infringement questions concern how THUNDERBOLT measures and interprets aspiration pressure.</h2><p className="lead">The asserted claims appear to require more than pressure sensing in the abstract. The likely disputes include whether the accused system detects a specified series of vacuum-pressure changes, determines baseline and peak pressure values, compares a pressure difference with a stored threshold, and produces the claimed alerts.</p><div className="callout"><b>Anticipated expert disciplines</b><p>Counsel may benefit from complementary testimony: an aspiration-thrombectomy or biofluid-mechanics expert for the physical and clinical operation, and a pressure-sensor, embedded-systems or signal-processing expert for the detection logic. A practicing neurointerventionalist may also be useful for method-of-use and instruction evidence.</p></div><div className="stakes"><div><small>Asserted family</small><strong>5 patents</strong><p>Five asserted claims identified in the public complaint analysis and linked below.</p></div><div><small>Commercial context</small><strong>$947.9M</strong><p>Penumbra-reported 2025 thrombectomy revenue; company-wide revenue was $1.404B.</p></div><div><small>Accused platform</small><strong>THUNDERBOLT</strong><p>Engine vacuum source, tubing/module and RED reperfusion catheters.</p></div></div></div></section>

    <section id="claims" className="claims shell"><header className="section-head"><div><span>02</span><p className="kicker">Asserted claims</p></div><h2>What “pressure pattern” means in this matter</h2></header><div className="claim-explainer"><div><h3>The alleged pattern</h3><p>The public complaint analysis identifies a limitation involving a <b>series of multiple increases and decreases in measured vacuum pressure</b>. The apparent infringement question is whether THUNDERBOLT detects that claimed sequence as an indication of catheter or clot conditions, rather than merely registering ordinary pump ripple, electrical noise, or a single pressure change.</p><p>Related claims in the asserted family reportedly address baseline and peak pressure, a difference between those values, comparison with a stored threshold, pressure-sensor placement, and distinct audible or visual signals. The filed complaint and exhibits should be used to confirm the allegation mapping.</p></div><div className="patent-list">{patents.map(([number,claim,url])=><a key={url} href={url} target="_blank" rel="noreferrer"><span>{number}</span><b>{claim}</b><em>Open patent ↗</em></a>)}</div></div></section>

    <section id="issues" className="issues shell"><header className="section-head"><div><span>03</span><p className="kicker">Technical issues</p></div><h2>Questions likely to require expert testimony</h2></header><div className="issue-list">{issues.map(x=><article key={x.n}><div className="issue-num">{x.n}</div><div><h3>{x.t}</h3><p className="question">{x.q}</p><p className="proof"><b>Potential evidence:</b> {x.p}</p></div><div className="discipline">{x.d}</div></article>)}</div></section>

    <section className="band"><div className="shell"><p className="kicker">Matter verification</p><div className="verification"><div><small>Public docket</small><p><b>Incuvate, LLC v. Penumbra, Inc.</b><br/>No. 4:26-cv-08658, U.S. District Court for the Northern District of California. Filed August 19, 2026 under 35 U.S.C. § 271.</p><a href={sources[0][2]} target="_blank" rel="noreferrer">Open docket ↗</a></div><div><small>Likely recipient for this research</small><p><b>Timothy B. Yoo</b><br/>Partner and Chair, IP Litigation Practice Group, Bird Marella; filing attorney for plaintiff.</p><a href="mailto:tyoo@birdmarella.com">tyoo@birdmarella.com</a><em>Official firm biography; not inferred.</em></div></div></div></section>

    <section id="experts" className="experts shell"><header className="section-head"><div><span>04</span><p className="kicker">Potential experts</p></div><h2>Ten candidates for further diligence</h2></header><p className="method">Ranked for plaintiff-side research priority based on subject-matter fit, relevant publications, public testimony and apparent independence-screen burden. The order is preliminary and is not a retention recommendation. Each email button opens an editable draft in the visitor&apos;s mail application; nothing is sent automatically.</p><div className="expert-grid">{experts.map(e=><article key={e.r} className="expert"><div className="rank">{String(e.r).padStart(2,"0")}</div><h3>{e.n}</h3><p className="role">{e.role}</p><dl><dt>Technical fit</dt><dd>{e.fit}</dd><dt>Relevant work</dt><dd>{e.work}</dd><dt>Public litigation experience</dt><dd>{e.lit}</dd><dt>Points for further diligence</dt><dd>{e.risk}</dd></dl><div className="source-links">{e.links.map(([l,u])=><a key={u} href={u} target="_blank" rel="noreferrer">{l} ↗</a>)}</div><div className="email-action"><a className="email-btn" href={expertMailto(e)}>Draft email to expert</a><a className="email-evidence" href={e.emailSource} target="_blank" rel="noreferrer">{e.email} · public source ↗</a></div></article>)}</div></section>

    <section className="band diligence"><div className="shell"><p className="kicker">Diligence before contact or retention</p><h2>Preliminary candidates; no conflicts or availability determination.</h2><div className="diligence-grid"><p>Run party, affiliate, counsel, inventor, funder and technology conflicts.</p><p>Confirm testimony history, exclusions, compensation, publications and deposition performance.</p><p>Investigate patents, licensing, grants, consulting and commercial interests.</p><p>Confirm role fit, availability and interest only after counsel authorizes outreach.</p></div><div className="excluded"><b>Initial independence screen:</b> known Penumbra-side experts in closely related PTAB matters were excluded from this plaintiff-side list. Candidate-specific issues above remain diligence questions, not conflict conclusions.</div></div></section>

    <section id="sources" className="sources shell"><header className="section-head"><div><span>05</span><p className="kicker">Sources and limitations</p></div><h2>Public record and research boundaries</h2></header><div className="source-list">{sources.map(([tag,title,url],i)=><a key={url} href={url} target="_blank" rel="noreferrer"><span>{String(i+1).padStart(2,"0")}</span><div><small>{tag}</small><p>{title}</p></div><b>↗</b></a>)}</div><div className="limits"><p>The docket and official attorney biography were verified directly. The technical analysis also relies on a paragraph- and claim-level public analysis of the complaint; its direct page was no longer live at final verification, and the public docket page did not provide the complaint PDF. Counsel should confirm allegation details against the filed complaint and exhibits.</p><p>No candidate was contacted. Availability, interest, compensation and conflicts were not checked. Public litigation-history searches are necessarily incomplete. This packet offers no legal conclusion on infringement, validity, damages, willfulness or inducement.</p></div></section>

    <footer><div className="shell"><div className="footer-mark">ER<span>·01</span></div><p>Independent preliminary research based on public information.</p><p>Complete packet · Prepared August 25, 2026 · Review copy</p></div></footer>
  </main>;
}
